type Profile {
    id: ID!
    profile_name: String
    user: User!
    age: String
    cool: Boolean
}

input ProfileInput {
    id: ID!
    profile_name: String    
    age: String
    cool: Boolean
}