type User {
    id: ID!
    name: String!
    email: String!
    age: Integer!    
}

input UserInput {
    id: ID
    name: String!   
    email: String!
    password: String!
    age: Integer!
}

type Query {
    users: [User!]!
    user(id: ID!): User!
}

type Mutation {
    createUser(data: UserInput!): User!
    updateUser(id: ID!, data: UserInput!): User!
    deleteUser(id: ID!): Boolean
}